[project]
name = "openchat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "ollama>=0.6.2",
    "streamlit>=1.63.0",
]

[project.scripts]
openchat = "openchat:main"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"
